name: Deploy Infraestrutura e Aplicação (Terraform + Ansible)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- JOB 1: PROVISIONAR A INFRAESTRUTURA ---
  terraform:
    name: 'Provisionar Infraestrutura (Terraform)'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar com Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve

  # --- JOB 2: CONFIGURAR A VM COM ANSIBLE ---
  ansible:
    name: 'Configurar VM (Ansible)'
    runs-on: ubuntu-latest
    needs: terraform # Depende do sucesso do job do Terraform

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar com Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # ### CORREÇÃO APLICADA AQUI ###
      # Juntamos a instalação e a execução em um único passo
      - name: Instalar dependências e Executar o Playbook Ansible
        run: |
          # 1. Instala as ferramentas base
          echo "Instalando dependências do sistema..."
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli ansible

          # 2. Instala a coleção do Ansible para o GCP
          echo "Instalando a coleção Ansible para Google Cloud..."
          ansible-galaxy collection install google.cloud
          
          # 3. Executa o playbook
          echo "Executando o Playbook..."
          ansible-playbook -i hosts deploy-cd.yml
