# Nome do Workflow
name: CI/CD - Deploy com Ansible na VM do GCP

# Gatilho: Executar sempre que houver um push na branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy-to-gcp-vm:
    name: Deploy com Ansible no GCP
    runs-on: ubuntu-latest

    steps:
      # ETAPA 1: FAZER O CHECKOUT DO CÓDIGO
      # Baixa os arquivos do seu repositório (playbook.yml, inventory.ini, etc.)
      # para o ambiente de execução do GitHub Actions.
      - name: Checkout do código do repositório
        uses: actions/checkout@v4

      # ETAPA 2: AUTENTICAÇÃO COM O GOOGLE CLOUD
      # Esta é a etapa que lê sua chave JSON a partir dos secrets do GitHub.
      # Ela cria um arquivo de credenciais temporário para as próximas etapas usarem.
      - name: Autenticação com Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # ETAPA 3: CONFIGURAÇÃO DO SDK DO GCLOUD
      # Esta é a etapa crucial que você mencionou.
      # Ela pega as credenciais da etapa anterior e configura a ferramenta 'gcloud'.
      # O plugin 'gcp_compute' do Ansible DEPENDE desta configuração para funcionar.
      - name: Configuração do gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          # Define o projeto correto, conforme seu arquivo inventory.ini.
          project_id: 'storied-radius-470316-f6'

      # ETAPA 4: INSTALAÇÃO DO ANSIBLE E DEPENDÊNCIAS DO GCP
      # O ambiente do GitHub Actions precisa do Ansible e das bibliotecas Python
      # que permitem a comunicação com a API do Google Cloud.
      - name: Instalar Ansible e a coleção GCP
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install ansible google-auth requests
          ansible-galaxy collection install google.cloud

      # ETAPA 5: EXECUÇÃO DO PLAYBOOK
      # Com tudo autenticado e instalado, esta etapa finalmente executa seu deploy.
      - name: Executar o Playbook Ansible
        run: |
          # O comando usa seu inventory.ini para encontrar a VM no GCP
          # e aplica as configurações do seu playbook.yml.
          # !! IMPORTANTE: Altere 'playbook.yml' se o seu arquivo tiver outro nome !!
          ansible-playbook -i inventory.ini deploy-cd.yml
