name: Deploy Infraestrutura e Aplicação (Terraform + Ansible)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- JOB 1: PROVISIONAR A INFRAESTRUTURA ---
  terraform:
    name: 'Provisionar Infraestrutura (Terraform)'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # --- Autenticação Direta com Chave JSON ---
      - name: Autenticar com Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply --auto-approve

  # --- JOB 2: CONFIGURAR A VM COM ANSIBLE ---
  ansible:
    name: 'Configurar VM (Ansible)'
    runs-on: ubuntu-latest
    needs: terraform # Depende do sucesso do job do Terraform

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # --- Autenticação Direta com Chave JSON ---
      - name: Autenticar com Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup de Ferramentas (gcloud e Ansible)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli ansible

      - name: Executar o Playbook Ansible
        run: |
          echo "Instalando a coleção Ansible para Google Cloud..."
          ansible-galaxy collection install google.cloud
          
          echo "Executando o Playbook..."
          ansible-playbook -i hosts deploy-cd.yml
