pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy-to-gcp-vm:
    name: Deploy com Ansible no GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código do repositório
        uses: actions/checkout@v4

      - name: Autenticação com Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configuração do gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'storied-radius-470316-f6'

      # ETAPA FINAL: INSTALAR E EXECUTAR DENTRO DE UM AMBIENTE ISOLADO E CONTROLADO
      # Esta etapa cria um ambiente virtual para garantir que o Ansible e suas
      # dependências estejam sempre juntos e sejam encontrados corretamente.
      - name: Instalar dependências e Executar o Playbook Ansible
        run: |
          # 1. Criar um ambiente virtual Python limpo
          python3 -m venv ansible_venv

          # 2. Ativar o ambiente virtual
          source ansible_venv/bin/activate

          # 3. Instalar o Ansible e TODAS as dependências do GCP dentro deste ambiente
          pip install --upgrade pip
          pip install ansible requests google-api-python-client google-auth-httplib2

          # 4. Instalar a coleção do Ansible para GCP
          ansible-galaxy collection install google.cloud

          # 5. Executar o playbook DE DENTRO do ambiente ativado
          echo "INFO: Ambiente pronto. Executando o playbook..."
          ansible-playbook -i inventory.ini deploy-cd.yml
