# Nome do Workflow
name: CI/CD - Deploy com Ansible na VM do GCP

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy-to-gcp-vm:
    name: Deploy com Ansible no GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código do repositório
        uses: actions/checkout@v4

      - name: Autenticação com Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configuração do gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'storied-radius-470316-f6'

      # ETAPA FINAL: Instalar e Executar dentro de um ambiente isolado
      - name: Instalar dependências e Executar o Playbook Ansible
        run: |
          # Criar um ambiente virtual Python limpo
          python3 -m venv ansible_venv

          # Ativar o ambiente virtual
          source ansible_venv/bin/activate

          # Instalar o Ansible e TODAS as dependências do GCP dentro deste ambiente
          pip install --upgrade pip
          pip install ansible requests google-api-python-client google-auth-httplib2

          # Instalar a coleção do Ansible para GCP
          ansible-galaxy collection install google.cloud

          # Executar o playbook DE DENTRO do ambiente ativado
          echo "INFO: Ambiente pronto. Executando o playbook..."
          ansible-playbook -i inventory.ini deploy-cd.yml
